#!/usr/bin/env bash
# Стенд под текущий worktree: сам подбирает свободные порты и поднимает
# docker-стек srs_<имя-воркtree>. Придуман для домашнего сервера, где веток
# много и искать свободную пару портов руками (как на Маке) надоело.
#
#   scripts/dev_stack.sh up        поднять стенд этого worktree
#   scripts/dev_stack.sh down      погасить (тома и порты остаются за воркtree)
#   scripts/dev_stack.sh rm        убрать совсем: тома, свою копию базы, порты
#   scripts/dev_stack.sh ls        все стенды: порты, ветка, живой ли
#   scripts/dev_stack.sh url       адрес стенда
#   scripts/dev_stack.sh logs api  логи сервиса
#   scripts/dev_stack.sh psql      psql в базу этого стенда
#   scripts/dev_stack.sh chown     забрать у root файлы, созданные контейнерами
#
# Что делает up:
#   1. присваивает воркtree свободную пару портов (nginx/api) и запоминает её
#      в docker-compose.worktree-override.yml — при следующем up порты те же;
#   2. кладёт рядом .env, скопированный из основного клона, с правкой портов;
#   3. Postgres НЕ поднимает — стенды ходят в общую dev-базу основного стека
#      (её published-порт), чтобы не держать по контейнеру и снимку на ветку;
#      --own-db делает воркtree свою копию базы на том же сервере;
#   4. Redis у каждого стенда СВОЙ, внутри проекта, без published-порта —
#      общий redis раньше менял порт при пересоздании и стенды молча вставали;
#   5. воркеров и beat не поднимает: они бы дублировали задачи основного стека
#      в общей базе (--with-workers, если ветка про celery).
set -euo pipefail

# --- где мы -----------------------------------------------------------------

WORKTREE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "${WORKTREE}"

# Основной клон: у worktree общий каталог .git, он лежит в клоне-владельце.
GIT_COMMON="$(git rev-parse --path-format=absolute --git-common-dir)"
MAIN_CLONE="$(dirname "${GIT_COMMON}")"

OVERRIDE="${WORKTREE}/docker-compose.worktree-override.yml"
MARKER="# generated by scripts/dev_stack.sh"

# Диапазоны портов: 18080+N — сайт, 18000+N — api напрямую. N=0 занят основным
# стеком (srs_dev), воркtree получают 1..49.
NGINX_BASE="${SRS_NGINX_BASE:-18080}"
API_BASE="${SRS_API_BASE:-18000}"
SLOTS="${SRS_SLOTS:-49}"

# --- вспомогательное --------------------------------------------------------

die() { echo "✗ $*" >&2; exit 1; }
say() { echo "$*" >&2; }

# Имя проекта из имени каталога воркtree. Хвост вида -01b21b, который дописывает
# Claude Code, режем: он ничего не говорит человеку, а имя проекта видно в ps.
project_name() {
  local base
  base="$(basename "${WORKTREE}")"
  if [[ "${WORKTREE}" == "${MAIN_CLONE}" ]]; then
    echo "srs_dev"
    return
  fi
  base="$(sed -E 's/-[0-9a-f]{6}$//' <<<"${base}")"
  base="$(tr '[:upper:]' '[:lower:]' <<<"${base}" | tr -c 'a-z0-9' '_' | sed -E 's/_+/_/g; s/^_//; s/_$//')"
  echo "srs_${base:0:32}"
}

port_busy() {
  local port="$1"
  # ss видит и docker-proxy, так что занятые контейнерами порты сюда попадают.
  ss -ltnH "sport = :${port}" 2>/dev/null | grep -q . && return 0
  # Плюс порты, уже закреплённые за другими воркtree, даже если те погашены.
  reserved_ports | grep -qx "${port}"
}

# Порты из override-файлов всех воркtree, кроме нашего. Читаем строку-заголовок
# «# ports: nginx=… api=…», а не YAML: у nginx порт записан с адресом привязки,
# и регулярка по строке портов на нём спотыкалась.
reserved_ports() {
  local wt
  while read -r wt; do
    [[ "${wt}" == "${WORKTREE}" ]] && continue
    [[ -f "${wt}/docker-compose.worktree-override.yml" ]] || continue
    slot_ports "${wt}/docker-compose.worktree-override.yml" | awk '{print $1; print $2}'
  done < <(worktree_paths)
}

# «nginx-порт api-порт база» из заголовка override-файла.
slot_ports() {
  awk '/^# ports:/ {
         for (i = 3; i <= NF; i++) { split($i, kv, "="); v[kv[1]] = kv[2] }
       }
       /^# db: / { db = $3 }
       END { print v["nginx"], v["api"], db }' "$1"
}

worktree_paths() {
  git -C "${MAIN_CLONE}" worktree list --porcelain | awk '/^worktree /{print $2}'
}

# Читает переменную из .env основного клона.
main_env() {
  local key="$1" default="${2:-}" val=""
  if [[ -f "${MAIN_CLONE}/.env" ]]; then
    val="$(grep -E "^${key}=" "${MAIN_CLONE}/.env" | tail -1 | cut -d= -f2- || true)"
  fi
  echo "${val:-${default}}"
}

# Контейнер общего postgres — тот, что публикует порт общей базы.
shared_pg_container() {
  local port="$1"
  docker ps --format '{{.Names}}\t{{.Ports}}' | awk -v p=":${port}->" '$0 ~ p {print $1; exit}'
}

# Значения текущего стенда (после того, как override уже создан).
load_slot() {
  read -r NGINX_PORT API_PORT DB_NAME < <(slot_ports "${OVERRIDE}")
}

compose() {
  docker compose --project-directory "${WORKTREE}" -p "${PROJECT}" \
    -f "${WORKTREE}/docker-compose.yml" -f "${OVERRIDE}" "$@"
}

# --- команды ----------------------------------------------------------------

cmd_up() {
  [[ "${WORKTREE}" == "${MAIN_CLONE}" ]] &&
    die "это основной клон, у него свой стек srs_dev с docker-compose.devserver.yml — скрипт для воркtree"

  local own_db=0 with_workers=0 rebuild_front=0
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --own-db) own_db=1 ;;
      --with-workers) with_workers=1 ;;
      --front) rebuild_front=1 ;;
      *) die "неизвестный ключ: $1" ;;
    esac
    shift
  done

  local pg_port pg_user pg_pass pg_db
  pg_port="$(main_env POSTGRES_PUBLISH_PORT 5433)"
  pg_user="$(main_env POSTGRES_USER saturday_runs)"
  pg_pass="$(main_env POSTGRES_PASSWORD saturday_runs)"
  pg_db="$(main_env POSTGRES_DB saturday_runs_lk)"

  [[ -n "$(shared_pg_container "${pg_port}")" ]] ||
    die "общий postgres на порту ${pg_port} не запущен — подними основной стек (srs_dev) или задай SRS_* вручную"

  local db_name="${pg_db}"
  [[ ${own_db} -eq 1 ]] && db_name="${PROJECT}"

  NGINX_PORT=""
  API_PORT=""
  DB_NAME=""
  if [[ -f "${OVERRIDE}" ]]; then
    grep -q "${MARKER}" "${OVERRIDE}" ||
      die "docker-compose.worktree-override.yml не наш (нет метки) — убери его руками, чтобы не затереть чужие настройки"
    load_slot
  fi

  if [[ -n "${NGINX_PORT}" && -n "${API_PORT}" ]]; then
    say "· порты этого воркtree уже закреплены: сайт ${NGINX_PORT}, api ${API_PORT}"
    [[ -n "${DB_NAME}" && ${own_db} -eq 0 ]] && db_name="${DB_NAME}"
  else
    local slot=""
    for ((i = 1; i <= SLOTS; i++)); do
      if ! port_busy $((NGINX_BASE + i)) && ! port_busy $((API_BASE + i)); then
        slot="${i}"
        break
      fi
    done
    [[ -n "${slot}" ]] || die "свободной пары портов не нашлось в ${SLOTS} слотах"
    NGINX_PORT=$((NGINX_BASE + slot))
    API_PORT=$((API_BASE + slot))
    say "· слот ${slot}: сайт ${NGINX_PORT}, api ${API_PORT}"
  fi

  if [[ ${own_db} -eq 1 ]]; then
    clone_db "${pg_port}" "${pg_user}" "${pg_db}" "${db_name}"
  else
    warn_migrations
  fi

  write_env "${NGINX_PORT}"
  write_override "${NGINX_PORT}" "${API_PORT}" "${db_name}" "${pg_port}"

  mkdir -p "${WORKTREE}/.cursor" "${WORKTREE}/data/og"

  if [[ ${rebuild_front} -eq 1 || ! -f "${WORKTREE}/frontend/dist/index.html" ]]; then
    say "· собираю фронт (node:22-alpine)…"
    # --user обязателен: под root node_modules и dist остаются root-овыми, и
    # потом `git worktree remove` падает с Permission denied без sudo.
    docker run --rm --user "$(id -u):$(id -g)" -e npm_config_cache=/tmp/.npm -e HOME=/tmp \
      -v "${WORKTREE}/frontend:/app" -w /app node:22-alpine \
      sh -c "npm ci --no-audit --no-fund && npm run build" >/dev/null ||
      die "сборка фронта упала"
  fi

  local services=(redis api nginx)
  if [[ ${with_workers} -eq 1 ]]; then
    services+=(worker beat)
    [[ ${own_db} -eq 0 ]] &&
      say "⚠ beat в общей базе будет дублировать расписание основного стека — лучше вместе с --own-db"
  fi

  say "· поднимаю ${PROJECT}: ${services[*]}"
  compose up -d --build "${services[@]}"

  wait_health "${NGINX_PORT}"
  cmd_url
}

# Копия dev-базы для воркtree — на том же сервере, отдельной базой. Нужна, когда
# в ветке своя миграция: катать её в общую базу нельзя, там сидят соседи.
clone_db() {
  local port="$1" user="$2" src="$3" dst="$4" pg
  pg="$(shared_pg_container "${port}")"
  if docker exec "${pg}" psql -U "${user}" -d postgres -tAc \
      "select 1 from pg_database where datname='${dst}'" | grep -q 1; then
    say "· своя база ${dst} уже есть"
    return
  fi
  say "· делаю копию базы ${src} → ${dst} (минуту-другую)…"
  docker exec "${pg}" psql -U "${user}" -d postgres -c "create database \"${dst}\"" >/dev/null
  docker exec "${pg}" sh -c \
    "pg_dump -U '${user}' -d '${src}' | psql -q -U '${user}' -d '${dst}'" >/dev/null
  say "· база ${dst} готова"
}

# Если в ветке есть своя миграция, а база общая — предупреждаем: alembic upgrade
# из этого воркtree поменяет схему всем соседям.
warn_migrations() {
  local own
  own="$(git -C "${WORKTREE}" diff --name-only origin/main...HEAD -- backend/alembic/versions 2>/dev/null | wc -l)"
  if [[ "${own}" -gt 0 ]]; then
    say ""
    say "⚠ в ветке ${own} своих файлов миграций, а база ОБЩАЯ с другими стендами."
    say "  Если собираешься катать alembic — подними стенд с --own-db."
    say ""
  fi
}

write_env() {
  local nginx_port="$1"
  [[ -f "${MAIN_CLONE}/.env" ]] || die "нет ${MAIN_CLONE}/.env — стенду неоткуда взять настройки"
  local host="${SRS_HOST:-$(main_env APP_BASE_URL | sed -E 's#https?://([^:/]+).*#\1#')}"
  host="${host:-127.0.0.1}"
  {
    grep -vE '^(NGINX_HTTP_PORT|APP_BASE_URL|POSTGRES_PUBLISH_PORT|REDIS_PUBLISH_PORT)=' "${MAIN_CLONE}/.env"
    echo "# --- правки dev_stack.sh под этот worktree ---"
    echo "NGINX_HTTP_PORT=${nginx_port}"
    echo "APP_BASE_URL=http://${host}:${nginx_port}"
    echo "POSTGRES_PUBLISH_PORT="
    echo "REDIS_PUBLISH_PORT="
  } >"${WORKTREE}/.env"
}

write_override() {
  local nginx_port="$1" api_port="$2" db="$3" pg_port="$4"
  local me="$(id -u):$(id -g)"
  # Логин и пароль не впечатываем — compose подставит их из .env воркtree.
  # Порт общей базы, наоборот, впечатываем: в .env он занулён, чтобы случайно
  # поднятый в воркtree postgres не подрался за него с основным стеком.
  cat >"${OVERRIDE}" <<YAML
${MARKER}
# worktree: ${WORKTREE}
# ports: nginx=${nginx_port} api=${api_port}
# db: ${db}
# Правится скриптом — руками сюда не дописывать, up перезапишет.
#
# user: питон пишет __pycache__ прямо в примонтированный backend/, и под root
# каталог воркtree становится неудаляемым без sudo. Здесь Docker настоящий
# (не Desktop с его подменой владельца), поэтому uid/gid задаём явно.
x-worktree-api: &worktree-api
  user: "${me}"
  environment:
    DATABASE_URL: postgresql+psycopg://\${POSTGRES_USER:-saturday_runs}:\${POSTGRES_PASSWORD:-saturday_runs}@host.docker.internal:${pg_port}/${db}
    HOME: /tmp
  extra_hosts:
    - "host.docker.internal:host-gateway"
  depends_on: !override
    redis:
      condition: service_healthy

services:
  api:
    <<: *worktree-api
    ports: !override
      - "${api_port}:8000"
  worker:
    <<: *worktree-api
  beat:
    <<: *worktree-api
  redis:
    ports: !override []
  nginx:
    ports: !override
      - "0.0.0.0:${nginx_port}:80"
YAML
}

wait_health() {
  local port="$1"
  for _ in $(seq 1 60); do
    if curl -fsS -m 2 "http://127.0.0.1:${port}/health" >/dev/null 2>&1; then
      say "· health 200"
      return
    fi
    sleep 2
  done
  say "⚠ /health не ответил за две минуты — смотри: scripts/dev_stack.sh logs api"
}

cmd_down() {
  [[ -f "${OVERRIDE}" ]] || die "стенд для этого воркtree не поднимался"
  compose down "$@"
  say "✓ ${PROJECT} погашен"
}

# Убрать стенд совсем: контейнеры, тома, свою копию базы и оба служебных файла.
# Общую базу не трогает никогда — дропаем только базу, названную по проекту.
cmd_rm() {
  [[ -f "${OVERRIDE}" ]] || die "стенд для этого воркtree не поднимался"
  load_slot
  compose down -v --remove-orphans || true
  if [[ "${DB_NAME}" == "${PROJECT}" ]]; then
    local pg_port pg_user pg
    pg_port="$(main_env POSTGRES_PUBLISH_PORT 5433)"
    pg_user="$(main_env POSTGRES_USER saturday_runs)"
    pg="$(shared_pg_container "${pg_port}")"
    if [[ -n "${pg}" ]]; then
      say "· дропаю свою базу ${DB_NAME}"
      docker exec "${pg}" psql -U "${pg_user}" -d postgres \
        -c "drop database if exists \"${DB_NAME}\" with (force)" >/dev/null
    fi
  fi
  cmd_chown
  rm -f "${OVERRIDE}" "${WORKTREE}/.env"
  say "✓ ${PROJECT} убран, порты освобождены"
}

# Вернуть себе файлы, которые контейнеры успели создать под root (__pycache__,
# node_modules у стендов, поднятых до появления `user:` в override). Иначе
# `git worktree remove` требует sudo, а его тут нет.
cmd_chown() {
  find "${WORKTREE}" -user 0 -print -quit | grep -q . || return 0
  say "· возвращаю себе root-овые файлы (через контейнер, sudo не нужен)"
  docker run --rm -v "${WORKTREE}:/w" alpine chown -R "$(id -u):$(id -g)" /w
}

cmd_url() {
  [[ -f "${OVERRIDE}" ]] || die "стенд для этого воркtree не поднимался"
  load_slot
  local host="${SRS_HOST:-$(main_env APP_BASE_URL | sed -E 's#https?://([^:/]+).*#\1#')}"
  say ""
  say "  сайт : http://${host:-127.0.0.1}:${NGINX_PORT}"
  say "  api  : http://${host:-127.0.0.1}:${API_PORT}/docs"
  say "  база : ${DB_NAME}"
  say ""
}

cmd_logs() {
  [[ -f "${OVERRIDE}" ]] || die "стенд для этого воркtree не поднимался"
  compose logs --tail 100 -f "$@"
}

cmd_psql() {
  load_slot
  local pg_port pg_user pg
  pg_port="$(main_env POSTGRES_PUBLISH_PORT 5433)"
  pg_user="$(main_env POSTGRES_USER saturday_runs)"
  pg="$(shared_pg_container "${pg_port}")"
  [[ -n "${pg}" ]] || die "общий postgres не запущен"
  local tty=(-i)
  [[ -t 0 ]] && tty=(-it)
  docker exec "${tty[@]}" "${pg}" psql -U "${pg_user}" -d "${DB_NAME}" "$@"
}

# Таблица всех стендов: чей воркtree, какая ветка, какие порты, поднят ли.
cmd_ls() {
  # Через column, а не printf: у printf ширина считается в байтах, и кириллица
  # разъезжается.
  ls_rows | column -t -s $'\t'
}

ls_rows() {
  printf 'ПРОЕКТ\tВЕТКА\tСАЙТ\tAPI\tСОСТОЯНИЕ\n'
  local wt name ov branch nport aport running
  while read -r wt; do
    ov="${wt}/docker-compose.worktree-override.yml"
    branch="$(git -C "${wt}" rev-parse --abbrev-ref HEAD 2>/dev/null || echo '?')"
    if [[ "${wt}" == "${MAIN_CLONE}" ]]; then
      name="srs_dev"
      nport="$(main_env NGINX_HTTP_PORT '-')"
      aport='-'
    else
      name="srs_$(basename "${wt}" | sed -E 's/-[0-9a-f]{6}$//' | tr '[:upper:]' '[:lower:]' | tr -c 'a-z0-9' '_' | sed -E 's/_+/_/g; s/^_//; s/_$//')"
      if [[ -f "${ov}" ]]; then
        read -r nport aport _ < <(slot_ports "${ov}")
      else
        nport='-'
        aport='-'
      fi
    fi
    if [[ "${nport}" == "-" ]]; then
      running="стенда нет"
    else
      running="$(docker compose ls --format json 2>/dev/null | grep -c "\"Name\":\"${name}\"" || true)"
      [[ "${running}" -gt 0 ]] && running="поднят" || running="погашен"
    fi
    printf '%s\t%s\t%s\t%s\t%s\n' "${name}" "${branch}" "${nport}" "${aport:--}" "${running}"
  done < <(worktree_paths)
}

# --- разбор команды ---------------------------------------------------------

PROJECT="$(project_name)"
cmd="${1:-up}"
[[ $# -gt 0 ]] && shift || true

case "${cmd}" in
  up) cmd_up "$@" ;;
  down) cmd_down "$@" ;;
  rm) cmd_rm ;;
  ls | list | status) cmd_ls ;;
  url) cmd_url ;;
  logs) cmd_logs "$@" ;;
  chown) cmd_chown ;;
  psql) cmd_psql "$@" ;;
  -h | --help | help)
    awk 'NR > 1 { if (!/^#/) exit; sub(/^# ?/, ""); print }' "${BASH_SOURCE[0]}" ;;
  *) die "не знаю команду «${cmd}»; см. scripts/dev_stack.sh --help" ;;
esac
