from fastapi import APIRouter

from app.api.routes import (
    achievements,
    admin,
    auth,
    avatars,
    backlog,
    blog,
    dashboard,
    demo,
    fastest,
    internal_bot,
    leaderboards,
    location_ratings,
    location_records,
    locations,
    media,
    newsletter,
    organizer,
    portal,
    profiles,
    public_profiles,
    releases,
    reports,
    runs,
    settings,
    stats,
    sweep_hq,
    sync,
    unified_protocol,
)

api_router = APIRouter()
api_router.include_router(auth.router)
api_router.include_router(avatars.router)
api_router.include_router(stats.router)
api_router.include_router(demo.router)
api_router.include_router(admin.router)
api_router.include_router(profiles.router)
api_router.include_router(dashboard.router)
api_router.include_router(achievements.router)
api_router.include_router(runs.router)
api_router.include_router(leaderboards.router)
api_router.include_router(fastest.router)
api_router.include_router(location_ratings.router)
api_router.include_router(location_records.router)
api_router.include_router(locations.router)
api_router.include_router(unified_protocol.router)
api_router.include_router(media.router)
api_router.include_router(organizer.router)
api_router.include_router(newsletter.router)
api_router.include_router(portal.router)
api_router.include_router(blog.router)
api_router.include_router(releases.router)
api_router.include_router(backlog.router)
api_router.include_router(sync.router)
api_router.include_router(settings.router)
api_router.include_router(public_profiles.router)
api_router.include_router(internal_bot.router)
api_router.include_router(reports.router)
api_router.include_router(sweep_hq.router)
